export const RoleConstants  = {
    ROLE_SUPERADMIN : "ROLE_SUPERADMIN",
    ROLE_ADMIN : "ROLE_ADMIN",
    ROLE_MANAGER : "ROLE_MANAGER",
    ROLE_DOCTOR : "ROLE_DOCTOR",
    LABORATORY : "LABORATORY",
    PHARMACY : "PHARMACY",
    PHYSIO : "PHYSIO",
    ANONYMOUS : "ANONYMOUS",
    OTHER : "OTHER",
    RECEPTIONIST : "RECEPTIONIST",
}
